name:
    sciatac_seq
channels:
    - conda-forge
    - bioconda
    - r
    - defaults
dependencies:
    - python>=3.7.3
    - r=3.5.1
    - samtools
    - bedtools
    - pysam
    - macs2
    - snakemake
    - pigz
    - bwa
    - trimmomatic=0.38
    - pysam=0.15.2
    - python_Levenshtein=0.12.0
